pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image using Dockerfile
                    docker.build("devops_final:${env.BUILD_NUMBER}", '-f Dockerfile .')
                }
            }
        }
        stage('Publish Docker Image') {
            steps {
                script {
                    // Authenticate with Docker Hub using credentials
                    docker.withRegistry('https://index.docker.io/v1/', 'dckr_pat_JVpfIwq6PwUTKUIMH4pF1Yk95W4') {
                        // Push the Docker image to Docker Hub
                        docker.image("devops_final:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }
    }
}

